# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gcdate',
            new_name='cdate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gcontents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gtitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gurl',
            new_name='url',
        ),
    ]
